### ISSUE TITLE
LunarGLASS build system broken with GLSL 14.0.0 or newer

### ISSUE THREAD

**Issue by natevm** [LunarG/LunarGLASS#77]
LunarGLASS appears to depend on the legacy HLSL and OGLCompiler libraries, which were removed late last year. 

See the release notes here for more details:
https://github.com/KhronosGroup/glslang/releases/tag/14.0.0 

This, unfortunately, means that the current LunarGLASS build system is broken.  

Could we get a resolution to this breaking issue triaged somehow?

**Comment by KarenGhavam-lunarG** [comment]
Yes, I am not surprised that the build of LunarGLASS has broken. glslang continues to move forward and is actively maintained and there is work occuring to clean up the ABI for glslang. I suspect fixing the build on your fork should not be difficult.

This project has not been actively maintained since 2017. As such the repository really should have been archived to make it clear it is no longer under any support. I plan to archive it soon.

**Comment by natevm** [comment]
If the project is not being actively maintained, then archiving is a good idea. 

Still, many of us could use a clear set of tools to optimize our GLSL code. If LunarGLASS is no longer maintained, how would you recommend optimizing glsl? 

In my specific case, I’m looking for a solid workflow for optimizing glsl for use in shadertoy/webgl. My current “guess and check” workflow is not very principled… 

I’m a bit nervous to down to SPIR-V, since I’d need the optimized code back in GLSL at the end of the optimization procedure to feed into shadertoy.

**Comment by danginsburg** [comment]
I haven't tried it myself, but could you do GLSL -> SPIR-V -> spirv-opt -> spirv-cross -> GLSL?

**Comment by natevm** [comment]
I haven’t tried this either. It’s on the todo list of things to try

**Comment by KarenGhavam-lunarG** [comment]
Dan's suggestion is a good path forward. Even though this repository is about the be archived and is no longer maintained, you can still use it. You could fork it as well and fix the build issue.
